Algoritmo "SemNome"
Var
     N: Inteiro
Procedimento Parouimpar(V: Inteiro)
Inicio
      Se (V%2=0) Entao
         Escreval("O número ", V, " é par")
      Senao
         Escreval("O número", V, " é Impar")
      Fimse
Fimprocedimento

Inicio
      EscrevaL("- - - LB SOLUÇÕES - - - ")
      Escreval("------Par Ou Ímpar------")
      Escreval(" ")
      Escreval("Digite Um Numero: ")
      Leia(N)
      Parouimpar(N)




Fimalgoritmo