Algoritmo "Algoritmo Somador Com Funçao"
Var
    N1, N2, Resp: inteiro
Funcao Soma(A, B: Inteiro) : Inteiro

Inicio

    Retorne A + B
    
Fimfuncao
Inicio
     Escreval("-------------------------")
     Escreval("-------LB SOLUÇÕES-------")
     Escreval("-------------------------")
     Escreval(" ")
     Escreval("Digite o 1º valor: ")
     Leia (N1)
     Escreval("Digite o 2º valor: ")
     Leia (N2)
     Resp <- Soma(N1, N2)
     Escreval("A Soma é: ", Resp)


Fimalgoritmo